project:
  type: website
  output-dir: docs
  pre-render: _pre-set-updated.py

website:
  title: "PPOL 6805 / DSAN 6750: GIS"
  favicon: "favicon.png"
  repo-url: "https://github.com/jpowerj/ppol6805"
  repo-actions: [source]
  repo-link-target: "_blank"
  sidebar:
    id: mainnav
    footer: "*Updated {{< env PPOL6805_LAST_UPDATED \"2024-08-28\" >}}*"
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: resources.qmd
        text: Resources
      - href: "recordings/"
        text: "Lecture Recordings"
      - href: https://georgetown.zoom.us/j/94074713027
        text: "ZOOM"
      - "---"
      - href: w01/index.qmd
        text: "Week 1: Aug 28"
      - href: w02/index.qmd
        text: "Week 2: Sep 4"
      - "---"
      - href: "https://chat.google.com/room/AAAAbGZ4pJk?cls=7"
        text: "Google Space  <i class='bi bi-box-arrow-up-right ps-1 align-self-center justify-self-center' style='font-size: 75%;'></i>"
      - href: "https://groups.google.com/a/georgetown.edu/g/dsan6750"
        text: "Email Archive <i class='bi bi-box-arrow-up-right ps-1 align-self-center justify-self-center' style='font-size: 75%;'></i>"
      - href: "https://forms.gle/1qmHmeXo94BaoN7d8"
        text: "Feedback <i class='bi bi-box-arrow-up-right ps-1 align-self-center justify-self-center' style='font-size: 75%;'></i>"

format:
  html:
    theme:
      light: default
      dark: darkly
    css: "/dsan-globals/jjstyles.css"
    toc: true
    include-in-header:
      text: "<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js' integrity='sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=='' crossorigin='anonymous' referrerpolicy='no-referrer'></script><script src='/sidebar.js'></script>"

