project:
  type: website
  output-dir: docs

website:
  title: "DSAN 6750 / PPOL 6805: Geographic Information Systems (GIS)"
  sidebar:
    id: mainnav
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



