project:
  type: website
  output-dir: docs
  pre-render: _pre-set-updated.py
  preview:
    port: 4321

website:
  title: "PPOL 6805 / DSAN 6750: GIS for Spatial Data Science"
  favicon: "favicon.png"
  repo-url: "https://github.com/jpowerj/ppol6805"
  repo-actions: [source]
  repo-link-target: "_blank"
  sidebar:
    id: mainnav
    title: "PPOL 6805 / DSAN 6750: GIS for Spatial Data Science"
    footer: "*Updated {{< env PPOL6805_LAST_UPDATED \"2024-08-28\" >}}*"
    contents:
      - href: index.qmd
        text: "<i class='bi bi-house pe-1'></i> Home"
      - href: syllabus.qmd
        text: Syllabus
      - href: resources.qmd
        text: Resources
      - href: "writeups/index.qmd"
        text: Writeups
      - href: final-project.qmd
        text: Final Project
      - href: "https://hchristy.georgetown.domains/_site"
        text: "Coding Workshop <i class='bi bi-box-arrow-up-right ps-1' style='font-size: 75%;'></i>"
      - "---"
      - href: w01/index.qmd
        text: "Week 1: Aug 27"
      - href: w02/index.qmd
        text: "Week 2: Sep 3"
      - href: w03/index.qmd
        text: "Week 3: Sep 10"
      - href: w04/index.qmd
        text: "Week 4: Sep 17"
      - href: w05/index.qmd
        text: "Week 5: Sep 24"
      - href: w06/index.qmd
        text: "Week 6: Oct 1"
      - href: w07/index.qmd
        text: "Week 7: Oct 8"
      - href: w08/index.qmd
        text: "Week 8: Oct 15"
      - href: w09/index.qmd
        text: "Week 9: Oct 22"
      - href: w10/index.qmd
        text: "Week 10: Oct 29"
      - href: w11/index.qmd
        text: "Week 11: Nov 5"
      - href: w12/index.qmd
        text: "Week 12: Nov 12"
      - href: w13/index.qmd
        text: "Week 13: Nov 19"
      - href: w14/index.qmd
        text: "Week 14: Dec 3"
      - "---"
      - href: "https://georgetown.zoom.us/j/92295251878?pwd=K8nOs3w9uRlj3mfn63bh0yazBpBbsC.1"
        text: "Zoom Link <i class='bi bi-box-arrow-up-right ps-1' style='font-size: 75%;'></i>"
        target: "_blank"
      - href: "https://georgetown.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=20a30444-5d14-4a4e-9994-b34400dc520d"
        text: "Recordings <i class='bi bi-box-arrow-up-right ps-1' style='font-size: 75%;'></i>"
        target: "_blank"
      - "---"
      - href: "https://guhub.io"
        text: "JupyterHub <i class='bi bi-box-arrow-up-right ps-1' style='font-size: 75%;'></i>"
        target: "_blank"
      - href: "https://jjacobs.me/meet"
        text: "Book Office Hour <i class='bi bi-box-arrow-up-right ps-1' style='font-size: 75%;'></i>"
        target: "_blank"
      - href: "https://chat.google.com/room/AAQAqBiPrZk?cls=7"
        text: "Google Space  <i class='bi bi-box-arrow-up-right ps-1 align-self-center justify-self-center' style='font-size: 75%;'></i>"
        target: "_blank"
      - href: "https://forms.gle/1qmHmeXo94BaoN7d8"
        text: "Feedback <i class='bi bi-box-arrow-up-right ps-1 align-self-center justify-self-center' style='font-size: 75%;'></i>"
        target: "_blank"

format:
  html:
    theme:
      light: default
      dark: darkly
    css: "/dsan-globals/jjstyles.css"
    toc: true
    link-external-newwindow: true
    link-external-icon: true
    include-in-header:
      text: "<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js' integrity='sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=='' crossorigin='anonymous' referrerpolicy='no-referrer'></script><link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/gh/dreampulse/computer-modern-web-font@master/fonts.css'><script src='/sidebar.js'></script>"

