---
title: "Additional Resources"
bibliography: "_PPOL6805.bib"
format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    callout-appearance: default
---

::: {.callout-note title="Update Log" collapse="true"}

* 2024 Sep 18: Added [*Geocomputation with Python*](https://py.geocompx.org/){target='_blank'}, the Python version of @lovelace_geocomputation_2024

:::

I'm going to try to dump **everything** I used to develop the course materials here---some of it I drew on explicitly (using images from books, for example), and the rest of it seeped into my mind implicitly over the course of preparing the materials. Explore them to see if their different approaches "click" in your mind more than my approach does!

## GIS with Python and R

All of the following textbooks have been chosen specifically because they are available for **free**, legally, online. In fact, the online versions are especially nice since you can interact with the maps, copy-and-paste the code into your own notebooks to run and modify it, and so on.

### Using R

The course's R material is drawn mainly from the following books, where I've tried to put them in order from most-used to least-used (in terms of the slides and assignments!):

* **@moraga_spatial_2024**: [*Spatial Statistics for Data Science: Theory and Practice with R*](https://www.paulamoraga.com/book-spatial/){target='_blank'}
  * This book, along with the video tutorial from Sherrie Xie linked below, will get you up-to-speed on the main topics in this course!
* **@lovelace_geocomputation_2024**: *[Geocomputation with R](https://r.geocompx.org/preface){target='_blank'}*
  * This book is *almost* my first choice, except that the figures and tables and etc. are generated in a kind of opaque way: if you have patience, and you want to reproduce a figure or table from the book as part of your own work, you can go to the book's GitHub repository to find the `.R` scripts, but personally I wasn't able to get a lot of them to run due to outdated/deprecated functions and libraries.
* **@pebesma_spatial_2023**: *[Spatial Data Science with Applications in R](https://r-spatial.org/book/){target='_blank'}*
  * This book is significantly more in-depth and goes into a level of detail that is probably overkill for this course, but if there is a particular topic you want to pursue for your final project, for example, this is where you can get a detailed account (from the creator of the `sf` library!)
* **@comber_geographical_2020**: *Geographical Data Science and Spatial Data Analysis: An Introduction in R* \[[`epub`](https://www.dropbox.com/scl/fi/rv7nr0v9276pvt4a0w32q/Lex-Comber-Geographical-Data-Science-and-Spatial-Data-Analysis_-An-Introduction-in-R.epub?rlkey=b2naf1aipbte9qng1z7x7x0v0&dl=1){target='_blank'}\]
  * I wanted to include this book as well because, if you're like me and you read ebooks on a device that requires `.epub` files... this is the only GIS book I was able to find in EPUB format!

### Using Python

* **@tenkanen_introduction_2024**: *[Introduction to Python for Geographic Data Analysis](https://pythongis.org/){target='_blank'}*
  * I found this book even more straightforward and organized as an overview, the only issue is that the portion on Spatial Data Science is not yet finished (as of early September 2024), so for that portion of the course @rey_geographic_2023 will be more helpful!
* **@rey_geographic_2023**: *[Geographic Data Science with Python](https://geographicdata.science/book/intro.html){target='_blank'}*
  * This book is especially nice if you're interested in applying GIS to public policy or the social sciences!
* **@graser_geocomputation_2025**: *[Geocomputation with Python](https://py.geocompx.org/){target='_blank'}
  * This is the Python companion book to @lovelace_geocomputation_2024, and is not yet completed, but I wanted to include it here in case you're looking for a pair of books where the Python and R content is **aligned** by chapter

## Videos

* For the quickest and most accessible intro to GIS using R I've ever found, you can watch [Sherrie Xie](https://www.med.upenn.edu/apps/faculty/index.php/g275/p8649466){target='_blank'}'s R Consortium workshop talk, [*Analyzing Geospatial Data in R*](https://www.youtube.com/watch?v=DD7bXonh-_E){target='_blank'}
* For a high-level overview, that will prepare you well for this course, see [Coursera: Introduction to GIS](https://www.coursera.org/learn/gis/lecture/S0HxB/why-gis-is-awesome){target='_blank'}, which is an online version of UC Davis' Introduction to GIS course.

## Other Courses

* If you're looking to dive headfirst into more intensive statistical modeling of geospatial data, definitely check out [Data Over Space and Time](https://www.stat.cmu.edu/~cshalizi/dst/20/){target='_blank'}, a course taught by Cosma Shalizi, a very cool professor of Statistics at Carnegie Mellon University.

## Cartography in General

* **@monmonier_how_2018**: *How to Lie with Maps* (3rd Edition). \[[`epub`](https://www.dropbox.com/scl/fi/6sb9hzp2ttugi9s6n5bnu/How-to-Lie-with-Maps_Mark-Monmonier.epub?rlkey=wx8yfep9rvhtsyldje5gdzp1t&dl=1){target='_blank'}\]
* **@wood_power_1992**: *The Power of Maps* \[[`pdf`](https://www.dropbox.com/s/lpu5xsrip7oinir/Denis%20Wood%20%26%20John%20Fels%20-%20The%20power%20of%20maps%20%281992%2C%20The%20Guilford%20Press%29%20-%20libgen.li.pdf?dl=0){target='_blank'}\]
  * I found Chapter 2, *Maps Are Embedded in a History They Help Construct*, especially helpful!

## Spatial Statistics / Spatial Data Science

Whereas the [GIS with Python and R](#gis-with-python-and-r) resources above are the key texts for this class, these books/resources dive deeper into the mathematical and statistical details of the models we look at towards the second half of the course. Here they're ordered from most to least-approachable (for someone just getting started with GIS), based on my subjective experience going through them over the summer!

* **@schabenberger_statistical_2004**: *Statistical Methods for Spatial Data Analysis* \[[`pdf`](https://www.dropbox.com/scl/fi/25gj53qitsdzw9kvcvfjf/Oliver-Schabenberger-Carol-A.-Gotway-Statistical-methods-for-spatial-data-analysis.pdf?rlkey=p5ih232gmxzm3zstvszux2big&dl=0){target='_blank'}\]
  * Despite being among the oldest on this list, this is the book that really "clicked" with me the most! If you're like me and the intensive math right at the beginning of @gaetan_spatial_2009 was a bit scary, for example, this one has much more gentle and slower-paced chapters at the beginning.
* **@gaetan_spatial_2009**: *Spatial Statistics and Modeling* \[[`pdf`](https://www.dropbox.com/scl/fi/ggrmx9gcekawzulcwspgj/Carlo-Gaetan-Xavier-Guyon-auth.-Spatial-Statistics-and-Modeling-2010.pdf?rlkey=a2e52hphc9ifaha8ra6ckbm2o&dl=1){target='_blank'}\]
  * This one has a pretty steep learning curve, as it starts right off the bat on the first page with some fairly intensive math introducing concepts like [random fields](https://en.wikipedia.org/wiki/Random_field){target='_blank'}. But, if you were a math major or you'd really like to know the mathematical underpinnings of the GIS methods we'll use towards the end of the course, this one may be for you!
* **@bivand_applied_2013**: *Applied Spatial Data Analysis with R* \[[`pdf`](https://www.dropbox.com/scl/fi/gm2mb07gylqmcwghz0e0t/Bivand-Roger-S._G-mez-Rubio-Virgilio_Pebesma-Edzer-Applied-spatial-data-analysis-with-R-2013.pdf?rlkey=y3ip1gzj1t9m2xgxlh9k66k2v&dl=1){target='_blank'}\]: This one has been superceded by @pebesma_spatial_2023, discussed in the [Using R](#using-r) section above, but I wanted to include it here since it was the textbook I used when first learning GIS with R back in the day... It is actually double-outdated since, not only is there a newer book but also a newer library, since this book uses the `sp` library rather than the newer `sf` library we've been using throughout the first few weeks of class!