
## Spatial Joins

```{r}
#| label: source-9im
library(tmap)
library(sf)
de_9im = function(x,
                  y,
                  object_names = c("x", "y"),
                  plot = TRUE,
                  funs = list(
                    "st_intersects",
                    "st_disjoint",
                    "st_touches",
                    "st_crosses",
                    "st_within",
                    "st_contains",
                    "st_contains_properly",
                    "st_overlaps",
                    "st_equals",
                    "st_covers",
                    "st_covered_by"
                    # ,
                    # "st_equals_exact" # requuires par argument
                    ),
                  include_relate = TRUE,
                  sparse = FALSE,
                  output = "character",
                  collapse = " ✓\n",
                  tmap = TRUE
                  ) {
  require("sf")
  if (is(x, "sfc") && is(y, "sfc")) {
    x = st_sf(data.frame(Object = object_names[1]), geometry = x)
    y = st_sf(data.frame(Object = object_names[2]), geometry = y)
  }
  xy = rbind(x, y)
  funs_matched = lapply(funs, match.fun)
  res = lapply(seq(length(funs)), function(i) {
    funs_matched[[i]](x, y, sparse = sparse)
  })
  res = unlist(res)
  if (output == "character") {
    res = unlist(funs)[res]
  }
  res_text2 = ""
  if (include_relate) {
    relation = sf::st_relate(x, y)
    res_text2 = paste0(" \nDE-9IM string: \n", relation) 
  }
  if (plot) {
    res_text1 = paste(res, collapse = collapse)
    collapse_no_break = gsub(pattern = "\\n", replacement = "", x = collapse)
    res_text1 = paste0(res_text1, collapse_no_break)
    message("Object x has the following spatial relations to y: ", res_text1, res_text2)
    if (tmap){
      res = de_9im_plot2(xy, label1 = res_text1, label2 = res_text2)
    } else {
      res = de_9im_plot(xy, label1 = res_text1, label2 = res_text2)
    }
  }
  res
}

de_9im_plot = function(xy, label1 = "test", label2 = "",
                       alpha = 0.5, show.legend = FALSE, x = 0.1, y = 0.95, 
                       theme = ggplot2::theme_void()) {
  require("ggplot2", quietly = TRUE)
  # browser()
  ggplot(xy) + 
    geom_sf(aes(fill = Object), alpha = alpha, show.legend = show.legend) +
    annotate("text", x = 0.1, y = 0.95, label = label1, hjust = "left", vjust = "top") +
    annotate("text", x = 0.1, y = 0.1, label = label2, hjust = "left", vjust = "bottom", 
             fontface = "italic") +
    theme
}

de_9im_plot2 = function(xy, label1 = "test", label2 = "",
                       alpha = 0.5, show.legend = FALSE, x = 0.1, y = 0.95, 
                       theme = ggplot2::theme_void()) {
  require("tmap", quietly = TRUE)
  # browser()
  # toDo: does not work yet
  st_crs(xy) = "EPSG:2180"
  tm_shape(xy) +
    tm_polygons(
      "Object",
      # fill.legend = tmap::tm_legend_hide(),
      
      fill_alpha = alpha,
                fill.scale = tmap::tm_scale(values = c("#E36939", "#6673E3"))) +
    tm_credits(label1, position = c(0.07, 0.62), just = "top") +
    tm_credits(label2, position = c(0.07, 0.32), fontface = "italic", just = "bottom") +
    tm_layout(frame = FALSE)
}
```

```{r}
#| label: create-9im-objects
xy2sfc = function(x, y) st_sfc(st_polygon(list(cbind(x, y))))
p1 = xy2sfc(x = c(0, 0, 1, 1,   0), y = c(0, 1, 1, 0.5, 0))
p2 = xy2sfc(x = c(0, 1, 1, 0), y = c(0, 0, 0.5, 0))
p3 = xy2sfc(x = c(0, 1, 1, 0), y = c(0, 0, 0.7, 0))
p4 = xy2sfc(x = c(0.7, 0.7, 0.9, 0.7), y = c(0.8, 0.5, 0.5, 0.8))
p5 = xy2sfc(x = c(0.6, 0.7, 1, 0.6), y = c(0.7, 0.5, 0.5, 0.7))
p6 = xy2sfc(x = c(0.1, 1, 1, 0.1), y = c(0, 0, 0.3, 0))
p7 = xy2sfc(x = c(0.05, 0.05, 0.6, 0.5, 0.05), y = c(0.4, 0.97, 0.97, 0.4, 0.4))
```

```{r}
# todo: add 3 more with line/point relations?
tmap::tmap_arrange(de_9im(p1, p2), de_9im(p1, p3), de_9im(p1, p4),
                   de_9im(p7, p1), de_9im(p1, p5), de_9im(p1, p6), nrow = 2)
```