---
title: "Week 1: {{< var w01.title >}}"
subtitle: "{{< var course.slides-subtitle >}}"
author: "{{< var course.author >}}"
institute: "{{< var course.institute >}}"
date: "August 28, 2024"
date-format: full
categories:
  - "Class Sessions"
format:
  revealjs:
    output-file: "slides.html"
    slide-number: true
    scrollable: true
    link-external-icon: true
    link-external-newwindow: true
    footer: "{{< var w01.footer >}}"
    include-in-header:
      text: "<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css'><link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH' crossorigin='anonymous'><script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js' integrity='sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz' crossorigin='anonymous'></script>"
    theme: [default]
    css: "../styles.css"
    revealjs-plugins:
      - simplemenu
    simplemenu:
      flat: true
      barhtml:
        header: "<div class='menubar'><span style='position: absolute; left: 8; padding-left: 8px;'><a href='./index.html'>&larr; Return to Notes</a></span><ul class='menu'></ul></div>"
      scale: 0.5
  html:
    output-file: "index.html"
    include-in-header:
      text: "<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css'><link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH' crossorigin='anonymous'><script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js' integrity='sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz' crossorigin='anonymous'></script><script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js' integrity='sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=='' crossorigin='anonymous' referrerpolicy='no-referrer'></script><script src='/jjcustom.js'></script>"
---

::: {.content-visible unless-format="revealjs"}

<center class='mb-3'>
<a class="h2" href="./slides.html" target="_blank">Open slides in new tab &rarr;</a>
</center>

:::

# Welcome to The Wonderful World of GIS! {data-stack-name="Why Me?"}

## Who Am I? Why Am I Teaching You? {.crunch-title}

* Started out as PhD student in **Computer Science**
  * UCLA: Algorithmic Game Theory
  * Stanford (MS): Economic Network Analysis
* Ended up with PhD in **Political Economy**
  * Columbia: "Computational Political Theory"

## My GIS Adventures

* High school project: **mine defusal** in Indochina
* As a **Telecommunications Engineer** for Huawei (HKUST)
* As an **Urban Economist** at UC Berkeley
  * Used, e.g., Google Maps API to evaluate effects of [**Suburbanization of Poverty**](https://www.brookings.edu/wp-content/uploads/2016/06/0120_poverty_paper.pdf){target='_blank'}

## My GIS 🤯 Moment

* Horrors of the """Vietnam""" """War""" did not end in 1975... Casualties from unexploded ordnance (cluster bombs) have continued to devastate the region, with over 219,000 victims:
  * [>105K in Vietnam](https://www.baldwin.senate.gov/imo/media/doc/Legacies%20of%20War%20Recognition%20and%20UXO%20Removal%20Act.pdf){target='_blank'}
  * [>50K in Laos](https://www.cnn.com/2016/09/05/asia/united-states-laos-secret-war/index.html){target='_blank'}
  * [>65K in Cambodia](https://apnews.com/article/bombs-land-mines-unexploded-ordnance-demining-564f0203aeb53aa95118a1396b907246){target='_blank'}

## At Huawei: Optimizing Cell Tower Placement

* 

## The Suburbanization of Poverty

* Since 2008, a person living in poverty in the US is more likely to be in a **suburb** than an "inner city"

# Why Should You Care About GIS? {data-stack-name="Why GIS?"}

* As a Human
* As a Data Scientist
* As a Public Policy Expert

## As Humans

* To understand the world around you!

## As Data Scientists

* All data scientists are expected to know how to analyze "standard" types of data: tabular, numeric data (think spreadsheets)
* However, you can **differentiate yourself** in the scary scary job market by developing a particular focus on some "non-standard" type: **text** data, **temporal** data, **signal** processing, and/or **geospatial** data!

## As Public Policy Experts

* Oftentimes, all it takes is one map to see why a policy has failed 😱

# So... What *Is* GIS? {data-stack-name="What is GIS?"}

## It's Completely Made Up {.smaller .crunch-title}

*Like, even more made up than other made-up technical terms...* 😵‍💫

{{< video https://www.youtube.com/watch?v=yjw_DuNkOUw height="500" width="100%" >}}

## What I Mean By "Made Up" {.smaller .crunch-title .crunch-ul}

* The **libraries** and **tools** we'll use are **specific** systems/methods for analyzing geospatial data
* **GIS** is an "umbrella term", which just vaguely refers to this entire universe of libraries/tools/techniques/approaches

```{=html}
<table>
<colgroup>
  <col style="width: 20%;">
  <col style="width: 40%;">
  <col style='width: 40%'>
</colgroup>
<thead>
<tr>
  <th class="tdc">Umbrella Term</td>
  <th class='tdc'>Concepts</td>
  <th class="tdc">Specific Skills</td>
</tr>
</thead>
<tbody>
<tr>
  <td class="tdc"><b>Coding</b></td>
  <td><div data-qmd="* Variables
* Control Flow
* Algorithms"></div></td>
  <td><div data-qmd="* Python
* R
* JavaScript"></div></td>
</tr>
<tr>
  <td class='tdc'><b>GIS</b></td>
  <td><div data-qmd="* Projections
* Vector vs. Raster
* Spatial Data Formats (shapefiles, `.geojson`)"></div></td>
  <td class='tdvc'><div data-qmd="* ArcGIS
* GeoPandas (Python)
* [`sf`](https://r-spatial.github.io/sf/){target='_blank'} (R)"></div></td>
</tr>
</tbody>
</table>
```

## ArcGIS

* For info on Georgetown's provision of ArcGIS (Online, Pro, and Desktop), see the [Library Guide](https://guides.library.georgetown.edu/esri_software){target='_blank'}

# How To Not Be Scared of Prerequisites {data-stack-name="Prereqs Without Fear"}

## I Am The Opposite of a Prereq-Stickler

* I genuinely believe that I can make the course accessible to you, meeting you **wherever you're at**, no matter what!
* To skip an entire spiel... Everyone learns at their own pace, and I structure my courses as best as I possibly can to adapt to your pace

## R and/or Python

